const ytTranslatorState = {
  sidebar: {
    updateTimer: null,
    isOpen: true,
    hasLoadedOpenState: false,
  },
  transcript: {
    retryCount: 0,
    activeRequest: 0,
    loadedVideoId: null,
    loadedTrackKey: "",
    segments: [],
    currentCaptionIndex: -1,
  },
  captionTracks: {
    available: [],
    selectedKey: "",
    preferredLanguageCode: "",
    preferredKind: "",
    hasUserSelectedForVideo: false,
  },
  captionRiver: {
    timer: null,
    isPausedForAd: false,
  },
  selection: {
    captionText: "",
    isSnapping: false,
  },
  chat: {
    activeRequest: 0,
    messages: [],
    messageCounter: 0,
    isWaitingForReply: false,
  },
  translate: {
    activeRequest: 0,
    isWaiting: false,
    result: "",
    chunks: [],
    error: "",
    errorDetails: null,
  },
  diagnostics: {
    isViewOpen: false,
    snapshot: null,
    error: "",
    isLoading: false,
    copyMessage: "",
  },
  playerCapture: {
    userAllowedCaptionCapture: false,
    activeVideoId: null,
    pendingVideoId: null,
    pendingTimer: null,
    pageCapturerInjected: false,
    pageCapturerReady: null,
    requestId: 0,
    lastCapturedCaptionUrl: "",
  },
};
